# Generated by Django 5.1 on 2024-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('emailId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_No', models.BigIntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
