# Generated by Django 5.1 on 2024-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('adminemailid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
